### ISSUE TITLE
Lower input size model

### ISSUE THREAD

**Issue by heethesh** [oandrienko/fast-semantic-segmentation#10]
Is there a lower input size model available?
Will it help with faster inference if the image size is reduced?
How do I go about training on lower resolution images, what are the changes required in the model?

**Comment by harora** [comment]
Yes , the training time significantly decreases with lower resolution images. I'm using 720x960 images and iteration time has decreased from 2.5 sec to 1.2 sec. I'm using 1080Ti.

**Comment by oandrienko** [comment]
Hey @heethesh, please excuse the delayed reply. @harora, thanks for the input. If you'd like to change the input size for inference, you can just do so with the flags in the export script.

For the training flow, you can change the input image size by specifying a cropping size within the training config. Look for the `random_image_crop` field in the configs. When I had trained, I stuck with 713x713 input crops for PSPNet and 1025x1025 for ICNet. From what I remember from the papers, the author suggests that you use as large of an input size as possible for performance. However, as expected, the computation increases significantly when training on larger images. In terms of inference, same rule will apply in terms of saving computation.

If you are not talking about crop size, but the actual size of the input image fetched from the TFRecord - there is currently a bug where I have hardcoded the cityscapes input image size of 1024x2048 in the `dataset_builder`. Hoping to do some cleanup this weekend or next and fix this so you can use whatever size you like.

**Comment by oandrienko** [comment]
Hey @heethesh,  I am sorry for the delayed update. I have not had the chance to work on this project for awhile but recent provided a larger update. I thought I would update this issue incase anyone else stumbles upon this.

With 42c6bbe, the dataset builder should now be able to parse datasets with TFRecords that have images that are not the standard 1024x2048 found in Cityscapes. I removed these hardcoded values. Let me know if you have any other issues.
