### ISSUE TITLE
Train on 2x8GB GPU Like 1080

### ISSUE THREAD

**Issue by ali-masoudi** [oandrienko/fast-semantic-segmentation#17]
hey guys
I don't have access to Titan XP, but I have access to 1080 GPU on the same machine, is there any way I could train the model?

**Comment by oandrienko** [comment]
Hey @ali-masoudi, thanks for your interest in the project. When I had trained, I went down to at most 11GB of memory with the 1080 Ti. This is what the current configs are tailored too.

I believe a regular 1080 only has 8GB so everything should work fine but you will need to play around with lower either the batch size, crop size, or both. As a note - the authors of PSPNet/ICNet mention that having a large batch size and crop size are important so I would expect your accuracy to go down if you lower these training parameters. I did noticed that smaller batch size hurt my performance as well but I would not be able to tell you by how much. Hope this helps.
