### ISSUE TITLE
Quantization aware training of ICNet

### ISSUE THREAD

**Issue by smohan10** [oandrienko/fast-semantic-segmentation#19]
Hi, 
I am trying to train ICNet without and with quantization. I followed your 2 stage process of training and got 69.3% and 64.7% mIoU for the stage 1 and stage 2. 

I would like to re-train stage 2 with quantization in mind. I see that you already have the create training graph inserted in the **create_training_model_losses**() method. 

There are 2 concerns here:
1. num_clones = 1
I see that training is in effect and checkpoints are created. The script ends successfully but when I inspect checkpoints, there are no quantization ops. I am expecting names like weights_quant, activation_quant in the example. 

2. num_clones = 2
I see this error:

tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot update edge, incompatible shapes: [32,9,9,256] and [2,33,33,256].

Have you seen this error? Have you tried using create training graph and has it worked without any issues? 

Keen to hear back from you!

**Comment by smohan10** [comment]
Any update on the above?

**Comment by oandrienko** [comment]
@smohan10 Hey, thanks so much for your interest in the project. I am really sorry for the delayed reply with this as the questions you posted are super interesting for me. 

I also initially had the intention to train with Quantization-aware training. However, I just never got the chance! But like you mentioned I included the small snipped within the codebase to do it if you like (with the `quantize_with_delay` field within the `train_config` proto). 

It looks like I had actually placed it too early in that one function you mentioned: it was being called on an almost empty graph as I was calling `quantize.create_training_graph` before actually calling the segmentation model's `predict` method. fc33e25 should fix this issue, but I have not tested it. In regards to your second issue, I have not seen that before. Can you try again and let me know if you get it? I recently merged a major commit that cleaned up a couple bugs.

If you do make any progress on the quantization, if you are open to it, please send me an email with the results! I would love to hear how it goes for you. As an interesting discussion point: if you are not using MobileNet as your backbone, I think you can get away with just doing Post-trained quantization. From what I remember reading, most networks (expect for MobileNet) keep their accuracy during Post-trained quantization quite well.
