### ISSUE TITLE
Key CascadeFeatureFusion/Conv/BatchNorm/beta not found in checkpoint

### ISSUE THREAD

**Issue by julienip** [oandrienko/fast-semantic-segmentation#21]
Thank you for spending all the time for us!

I have applied your suggestions, checked out master and renamed the nodes since I trained pspnet already.
At stage 1 of the training, when I run the export.py script, I have the following issue:
_### _NotFoundError (see above for traceback): Key CascadeFeatureFusion/Conv/BatchNorm/beta not found in checkpoint
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]__

**Comment by oandrienko** [comment]
@julienip thanks for following up. Can you also run `python -m tensorflow.python.tools.inspect_checkpoint --file_name <YOU_PRUNED_CHECKPOINT_FILE>` and show me the results? I can look at it today! I want to make sure the rename script worked for you I believe that's your problem.

**Comment by julienip** [comment]
@oandrienko I restarted a new training for pspnet and the export.py script still fails.
Please see attached the result of the inspection command 
python3 -m tensorflow.python.tools.inspect_checkpoint --file_name pspnet_1.0_713_resnet_v1_TRAIN/model.ckpt-2792 > inspect_checkpoint.txt 

[inspect_checkpoint.txt](https://github.com/oandrienko/fast-semantic-segmentation/files/3139875/inspect_checkpoint.txt)

**Comment by oandrienko** [comment]
@julienip are you trying to export PSPNet or ICNet? In your error message it is mentioning `CascadeFeatureFusion` layer, which is ICNet specific. But the checkpoint you send is for ICNet. Can you clarify?

**Comment by julienip** [comment]
@oandrienko My bad.... I was exporting wrongly pspnet...
The export worked with my first training of icnet.

Now When I run the compress.py script, I have the keyError again:

Traceback (most recent call last):
  File "compress.py", line 103, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "compress.py", line 96, in main
    compressor.compress(FLAGS.input_checkpoint)
  File "/workspace/fast-semantic-segmentation-master/libs/filter_pruner.py", line 381, in compress
    self.neighbors = self._create_adjacency_list(self.output_node)
  File "/workspace/fast-semantic-segmentation-master/libs/filter_pruner.py", line 115, in _create_adjacency_list
    output_node = self.nodes_map[output_node_name]
KeyError: 'Predictions/Conv/Conv2D'

Running the inspection on icnet model:
[inspect_checkpoint.txt](https://github.com/oandrienko/fast-semantic-segmentation/files/3139962/inspect_checkpoint.txt)

**Comment by oandrienko** [comment]
@julienip No worries that's what I figured!

For compression, it looks like the latest inspection output you sent is also from PSPNet, not ICNet. Maybe you sent me the wrong inspection output? I am thinking that maybe you are not running compression on the output checkpoints from export. Please let me know!

**Comment by julienip** [comment]
Sorry, I sent the old one... This is the inspection for ICNET
[inspect_checkpoint.txt](https://github.com/oandrienko/fast-semantic-segmentation/files/3139984/inspect_checkpoint.txt)

**Comment by oandrienko** [comment]
Thanks, this looks correct. However, seems like there are still training variables in the checkpoint. I can double check tonight, but from what I remember the “AuxOutput” nodes should not be added when saving the inference checkpoints in the export script. Can you clarify if you are running the inspection script on the checkpoints being output from the export script?

**Comment by julienip** [comment]
@oandrienko Ok no, dont look at it tonight. I think you should not reply to me after at least 1 day. I made some stupid mistake. Wrong path mainly...
It is working and the issue can be closed. :P
Thanks so much!

**Comment by oandrienko** [comment]
@julienip No worries - I'm glad it works for you! Let me know if you run into any more issues.
