### ISSUE TITLE
For c++ pb

### ISSUE THREAD

**Issue by engineer1109** [oandrienko/fast-semantic-segmentation#23]
Is the input node name "inputs" ?
output nodename "Predictions/Conv/Conv2D" ?

And what size and type is the input and output tensor?

**Comment by oandrienko** [comment]
@engineer1109 The input and output node names for the frozen graph def are set in the export script. I named the input placeholder `inputs` and the output identity op `outputs`. The sizes are specified by the export script flags and your model definition. The types are uint for the input and float for the output.

I can make sure to add this to the documentation later and make the input types are flags. Hope this helps.

**Comment by engineer1109** [comment]
The output node name is predictions_1.
the input shape is 1024 2048 3
the output shape is  1024 2048.
I have finished my c++ ICNet code .
Thank you.

**Comment by oandrienko** [comment]
Right, the name is `predictions` for the output - my mistake. Glad it worked!

**Comment by sctrueew** [comment]
> The output node name is predictions_1.
> the input shape is 1024 2048 3
> the output shape is 1024 2048.
> I have finished my c++ ICNet code .
> Thank you.

Hi @engineer1109 

Could you please share your C++ code?

**Comment by engineer1109** [comment]
@zpmmehrdad It has been one year. I need to find my code.

**Comment by sctrueew** [comment]
@engineer1109 thanks for your reply
