### ISSUE TITLE
How to execute the sample code?

### ISSUE THREAD

**Issue by a9311072** [oandrienko/fast-semantic-segmentation#25]
as the sample link, https://modeldepot.io/oandrienko/icnet-for-fast-segmentation
I found there is an issue as below when I execute to the **run_inference_for_single_image()** to get the tensor.name and it can not be found. I tried many methods but it doesn't work.
Does anyone know how to convert normally?

KeyError: "The name 'inputs:0' refers to a Tensor which does not exist. The operation, 'inputs', does not exist in the graph."

Environment, 
Cuda: 9.0
Cudnn: 7.0.5
Tensorflow: 1.8

**Comment by oandrienko** [comment]
Hey thanks for your interest. Which checkpoints do you use? The ones from ModelDepot or the Model Zoo? I need to update the models on ModelDepot they are a bit outdated.

**Comment by oandrienko** [comment]
Going to close this for now since I haven't heard back. Not exactly sure the issue you are having. Reopen if you are still having trouble.
