### ISSUE TITLE
Using multi-modal data for training

### ISSUE THREAD

**Issue by prajakta-13** [oandrienko/fast-semantic-segmentation#27]
Hi Oandrienko,

I have tried using the repository for training segmentation models on various datasets such as Cityscapes, camvid and custom datasets as well for various numbers of classes. The model works fine. 

However if I try to use multiple datasets (Annotated for same classes) together, it brings the accuracy down to a great extent. 
Is there any specific requirement for the data to be captured from the same camera or so?

Prajakta

**Comment by oandrienko** [comment]
Hey Prajakta, do you mean have a single TFRecord with frames from various datasets? The project should not have any issues handling this as long as you construct your TFRecord the correct way.

I suspect your issue might be hyperparameter related. 

I will close this for now but feel free is open if you have any other questions.
