### ISSUE TITLE
Could not find pipeline.config in Pre-trained ICNet and PSPNet Models archives

### ISSUE THREAD

**Issue by lakshminarayanareddybn** [oandrienko/fast-semantic-segmentation#30]
Hi,
I am trying to use the pretrained models provided in the link for validation
https://github.com/oandrienko/fast-semantic-segmentation/blob/master/docs/model_zoo.md#validating-pre-trained-models

the validation scripts eval.py and inference.py expects parameter  --config_path=0818_icnet_0.5_1025_resnet_v1/pipeline.config. 

but 0818_icnet_0.5_1025_resnet_v1 dont have "pipeline.config" in the downloaded tar.gz file.

please can you check it.

Thanks & Regards
Lakshminarayana reddy

**Comment by lakshminarayanareddybn** [comment]
s

**Comment by ShreyNiraula** [comment]
Hi, you have closed the issue. Did you find, I am having the same problem
